name: Build documentation

on:
  push:
    branches:
      - release
      - doc-builder*

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@maim
    with:
      commit_sha: ${{ github.event.pull_request.head.sha }}
      package: course
      path_to_docs: course/chapters/
      additional_args: --not_python_module
      languages: en es