# This is a basic workflow to help you get started with Actions

name: Deploy

on:
  push:
    branches:
      - master
      - ci_*
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        run: cd ~/moon-landing && bash course-deploy.sh

      - name: Open to the world
        run: pm2 restart course
